export enum LeaveType {
  ANNUAL = 'ANNUAL',
  CASUAL = 'CASUAL',
  HALF_DAY = 'HALF_DAY',
  SICK = 'SICK',
  MATERNITY = 'MATERNITY',
  PATERNITY = 'PATERNITY',
  LOSS_OF_PAY = 'LOSS_OF_PAY',
}

export enum LeaveStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}
