export enum Role {
  CEO = 'CEO',
  EXECUTIVE = 'EXECUTIVE',
  ADMIN = 'ADMIN',
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  HR = 'HR',
  HR_MANAGER = 'HR_MANAGER',
  MANAGER = 'MANAGER',
  TEAM_MANAGER = 'TEAM_MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  ACCOUNTANT = 'ACCOUNTANT',
}
